config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'

  resources :users
  resources :blog_posts

  get '/about', to: 'pages#about'
  get '/sample_blog_post', to: 'pages#sample_blog_post'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/user_profile', to: 'sessions#show'
  get '/user_profile/edit', to: 'sessions#edit'
  patch '/user_profile', to: 'sessions#update'
  get '/recent_blog', to: 'pages#recent_blog'
  get '/dashboard', to: 'pages#dashboard'
  get '/import', to: 'blog_posts#upload'
  post '/import', to: 'blog_posts#import'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :user
  has_many :blog_post_tag, dependent: :destroy
  has_many :tag, through: :blog_post_tag

  validates :title, presence: true,
					 length: { maximum: 150 }
  validates :summary, length: { maximum: 250 }
  validates :content, presence: true
  validates :title_image_url, length: { maximum: 250 }

  searchable do
  	string :title
  	string :summary

  	text :title
  	text :summary
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
	require 'csv'

	def index
		redirect_to root_path unless session[:user_id]
		decorator = BlogPostsDecorator.new(self)
		@blog_posts = decorator.decorate_for_index(BlogPost.order(created_at: :ASC))
	end

	def show
		@blog = BlogPost.find(params[:id])
		@blog.view_count = @blog.view_count + 1
		@blog.update_attribute(:view_count, @blog.view_count)

		decorator = BlogPostsDecorator.new(self)
		@blog_post = decorator.decorate_for_show(BlogPost.find(params[:id]))
	end

	def new
		redirect_to root_path unless session[:user_id]
		@blog_post = BlogPost.new
	end

	def upload
		redirect_to root_path unless session[:is_admin]
	end

	def import
		redirect_to root_path unless session[:is_admin]
		file_path = params[:file].path
		@rows = CSV.read(file_path)

		ActiveRecord::Base.transaction do
			@rows[1..-1].each do |row|
				@user = User.where(email: row[1]).take
				if(@user == nil)
					@user = User.new(
						name: row[0], 
						email: row[1], 
						password: 'default', 
						is_admin: false, 
						activity_count: 0
					)
					@user.save
				end
				@blog_post = BlogPost.new(title: row[2], summary: row[3], content: row[4], title_image_url: row[5], user: @user, view_count: 0)
				@blog_post.save
			end
		end

	    redirect_to root_path
	end

	def edit
		redirect_to root_path unless session[:user_id]
		@blog_post = BlogPost.find(params[:id])
		decorator = BlogPostsDecorator.new(self)
		@blog_post_tag = decorator.decorate_for_show(BlogPost.find(params[:id]))
	end

	def create
		redirect_to root_path unless session[:user_id]
		@blog_post = BlogPost.new(blog_post_params)

		if @blog_post.valid?
			ActiveRecord::Base.transaction do
				@blog_post.save
				save_tag(id_blog_post: @blog_post.id, save_type: 'new')
			end
				#raise 'a'
			redirect_to @blog_post
		else
			render 'new'
		end
	end

	def update
		redirect_to root_path unless session[:user_id]
		@blog_post = BlogPost.find(params[:id])

		if @blog_post.valid?
			ActiveRecord::Base.transaction do
				@blog_post.update(blog_post_params)
				save_tag(id_blog_post: params[:id], save_type: 'update')
			end
			redirect_to @blog_post
		else
			render 'edit'
		end
	end

	def destroy
		redirect_to root_path unless session[:user_id]
		@blog_post = BlogPost.find(params[:id])
		@blog_post.destroy

		redirect_to blog_posts_path
	end

	private
		def blog_post_params
			params.require(:blog_post).permit(:title, :summary, :content, :title_image_url, :user_id, :view_count)
		end

		def save_tag(id_blog_post:, save_type:)
			if(save_type == 'update')
				@blog_post_tag_to_delete = BlogPostTag.where(blog_post_id: id_blog_post)
				
				@blog_post_tag_to_delete.each do |tag_detail|
					tag_detail.destroy
				end
			end
			@tag_params = params[:tag].split(' ')
			@tag_params.each do |tag_param|
				@tag = Tag.where(name: tag_param).take
				if(@tag == nil)
					@tag = Tag.new(name: tag_param)
					# @tag.name = tag_param
					@tag.save
				end

				# @blog_post_tag = BlogPostTag.new
				# @blog_post_tag.blog_post = BlogPost.find(id_blog_post)
				# @blog_post_tag.tag = @tag
				# @blog_post_tag.save

				blog_post = BlogPost.find(id_blog_post)
				BlogPostTag.new(blog_post: blog_post, tag: @tag)
						   .save
			end 
		end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_form.html.erb
<div class="container">
	<div class="row">
		<%= form_for :blog_post, html: {class: 'form-horizontal'}, url: yield(:url_target), method: yield(:method) do |f| %>

			<% if @blog_post.errors.any? %>
				<div id="error_explanation" class="col-sm-12 alert alert-danger">
					<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
					<h2 class="text-center">
						<%= pluralize(@blog_post.errors.count, "error") %> prohibited
						this post from being saved
					</h2>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :title, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_field :title, class: 'form-control' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>

			<% if @blog_post.errors.include? :title %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Title ' + @blog_post.errors.messages[:title].join(' ') %>
					</div>
					<div class="col-sm-3"></div>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :summary, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_field :summary, class: 'form-control' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>

			<% if @blog_post.errors.include? :summary %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Summary ' + @blog_post.errors.messages[:summary].join(' ') %>
					</div>
					<div class="col-sm-3"></div>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :content, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_area :content, class: 'form-control' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>

			<% if @blog_post.errors.include? :content %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Content ' + @blog_post.errors.messages[:content].join(' ') %>
					</div>
					<div class="col-sm-3"></div>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :title_image_url, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_field :title_image_url, class: 'form-control' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>

			<% if @blog_post.errors.include? :title_image_url %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Image url ' + @blog_post.errors.messages[:title_image_url].join(' ') %>
					</div>
					<div class="col-sm-3"></div>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= label_tag :tag, 'Tag', class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= text_field_tag :tag, yield(:tag), class: 'form-control', placeholder: 'Tag separated by space' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>

			<%= f.hidden_field :view_count, value: 0 %>
			<%= f.hidden_field :user_id, value: session[:user_id] %>
			    
			<div class="col-sm-12">
				<%= f.submit class: 'btn btn-default center-block' %>
			</div>
		<% end %>
		<div class="col-sm-12 text-center">
			</br>
			<%= link_to 'Back', blog_posts_path %>
		</div>
	</div>
</div>

app/views/blog_posts/edit.html.erb
<% provide(:title, 'Edit Post') %>
<% provide(:heading, 'Edit Post') %>
<% provide(:subheading, 'Edit Post of Clean Blog') %>
<% provide(:bg, 'post-bg.jpg') %>
<% provide(:url_target, blog_post_path(@blog_post)) %>
<% provide(:method, :patch) %>
<% provide(:tag, @blog_post_tag.tag_joined) %>

<%= render 'form' %>

app/views/blog_posts/index.html.erb
<% provide(:title, 'Blog Posts') %>
<% provide(:heading, 'Blog Posts') %>
<% provide(:subheading, 'Blog Posts on Clean Blog') %>
<% provide(:bg, 'post-bg.jpg') %>

<div class="container">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
			<%= link_to 'Add Post', new_blog_post_path %> &nbsp;
			<%= link_to 'Import CSV', import_path if is_admin?%>
			<hr>
			<% @blog_posts.reverse_each do |blog_post| %>

				<% if blog_post.user_id == session[:user_id] %>
		            <div class="post-preview">
	                	<%= blog_post.link_to_show %>
		                <p class="post-meta">Posted by <%= blog_post.link_to_user %> on <%= blog_post.created_at %> &nbsp; 
		                	<% if logged_in? %>
		                	<%= blog_post.link_to_edit %> - <%= blog_post.link_to_delete %> </p>
	              			<% end %>
		            </div>
	            	<hr>
		        <% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/blog_posts/new.html.erb
<% provide(:title, 'Add Post') %>
<% provide(:heading, 'Add Post') %>
<% provide(:subheading, 'Add Post to Clean Blog') %>
<% provide(:bg, 'post-bg.jpg') %>
<% provide(:url_target, blog_posts_path) %>
<% provide(:method, :post) %>

<%= render 'form' %>

app/views/blog_posts/show.html.erb
<% provide(:title, 'Blog Post') %>
<% provide(:bg, @blog_post.title_image_url) %>
<% provide(:post_title, @blog_post.title) %>
<% provide(:post_summary, @blog_post.summary) %>
<% provide(:poster, @blog_post.user_name) %>
<% provide(:date_created, @blog_post.created_at) %>


<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <% if logged_in? && (@blog_post.user_id == session[:user_id]) %>
                    <ul class="pager">
                        <li class="previous">
                            <%= @blog_post.link_to_edit %>
                        </li>
                        <li class="previous">
                            <%= @blog_post.link_to_delete %>
                        </li>
                    </ul>
                    </br>
                <% end %>
                <%= @blog_post.content %>
                <ul class="pager">
                    <% @blog_post.tag.each do |tag| %>
                        <li class="previous">
                            <a href="<%=recent_blog_path(q: tag)%>"><%= tag %></a>
                        </li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</article>

app/views/blog_posts/upload.html.erb
<% provide(:title, 'Import CSV') %>
<% provide(:heading, 'Import CSV') %>
<% provide(:subheading, 'Add Post from CSV file to Clean Blog') %>
<% provide(:bg, 'post-bg.jpg') %>

<div class="container">
	<div class="row">
		<%= form_tag({action: :import}, multipart: true, class: "form-horizontal", enforce_utf8: false) do %>
		  	<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= label_tag :file, nil, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= file_field_tag :file, class: 'form-control' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>
			<%= submit_tag 'Submit', class: 'btn btn-default center-block' %>
		<% end %>
	</div>
</div>