config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'

  resources :users
  resources :blog_posts

  get '/about', to: 'pages#about'
  get '/sample_blog_post', to: 'pages#sample_blog_post'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/user_profile', to: 'sessions#show'
  get '/user_profile/edit', to: 'sessions#edit'
  patch '/user_profile', to: 'sessions#update'
  get '/recent_blog', to: 'pages#recent_blog'
  get '/dashboard', to: 'pages#dashboard'
  get '/import', to: 'blog_posts#upload'
  post '/import', to: 'blog_posts#import'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	has_many :blog_posts
	validates :name, presence: true,
					 length: { maximum: 45 }
	validates :email, presence: true,
					  length: { maximum: 45 },
					  uniqueness: { case_sensitive: false },
					  format: { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
	validates :password, presence: true,
					  length: { maximum: 45 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		decorator = UsersDecorator.new(self)
		@users = decorator.decorate_for_index(User.order(id: :ASC))
	end

	def show
		decorator = UsersDecorator.new(self)
		@user = decorator.decorate_for_show(User.find(params[:id]))
	end

	def new
		@user = User.new
		
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)

		if @user.save
			redirect_to @user
		else
			render 'new'
		end
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy

		redirect_to users_path
	end

	private
		def user_params
			params.require(:user).permit(:name, :email, :password, :is_admin, :activity_count)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
	<div class="row">
		<%= form_for :user, :html => {class: 'form-horizontal'}, url: yield(:url_target), method: yield(:method) do |f| %>

			<% if @user.errors.any? %>
				<div id="error_explanation" class="col-sm-12 alert alert-danger">
					<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
					<h2 class="text-center">
						<%= pluralize(@user.errors.count, "error") %> prohibited
						this user from being saved
					</h2>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :name, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_field :name, class: 'form-control' %>
			    </div>
			    <div class="col-sm-3"></div>
			</div>

			<% if @user.errors.include? :name %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Name ' + @user.errors.messages[:name].join(' ') %>
					</div>
					<div class="col-sm-3"></div>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :email, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_field :email, class: 'form-control' %>
			    </div>
				<div class="col-sm-3"></div>
			</div>

			<% if @user.errors.include? :email %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Email ' + @user.errors.messages[:email].join(' and ') %>
					</div>
				    <div class="col-sm-3"></div>
				</div>
			<% end %>

			<div class="form-group col-sm-12">
				<div class="col-sm-3"></div>
				<%= f.label :password, class: 'control-label col-sm-2' %>
			    <div class="col-sm-4">
			    	<%= f.text_field :password, class: 'form-control' %>
			    </div>
				<div class="col-sm-3"></div>
			</div>

			<% if @user.errors.include? :password %>
				<div class="form-group col-sm-12">
					<div class="col-sm-5"></div>
					<div class="col-sm-4 text-center" style="color: red;">
					    <%= 'Password ' + @user.errors.messages[:password].join(' ') %>
					</div>
				    <div class="col-sm-3"></div>
				</div>
			<% end %>

			<% if is_admin? %>
				<div class="form-group col-sm-12">
					<div class="col-sm-3"></div>
					<%= f.label :is_admin, 'Is admin?', class: 'control-label col-sm-2' %>
					<div class="col-sm-4">
						<%= f.check_box :is_admin, { class: '' }, "true", "false" %>
					</div>
					<div class="col-sm-3"></div>
				</div>
			<% end %>

			<%= f.hidden_field :activity_count, value: 0 %>

			<div class="col-sm-12">
				<%= f.submit class: 'btn btn-default center-block' %>
			</div>
		<% end %>
		<div class="col-sm-12 text-center">
			</br>
			<%= link_to 'Back', users_path %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<% provide(:heading, 'Edit User') %>
<% provide(:subheading, 'Edit User of Clean Blog') %>
<% provide(:bg, 'about-bg.jpg') %>
<% provide(:url_target, user_path(@user)) %>
<% provide(:method, :patch) %>

<%= render 'form' %>

app/views/users/index.html.erb
<% provide(:title, 'User List') %>
<% provide(:heading, 'User List') %>
<% provide(:subheading, 'List of User on Clean Blog') %>
<% provide(:bg, 'about-bg.jpg') %>

<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<%= link_to 'Add User', new_user_path if is_admin? %>
			<table class="table">
				<tr>
					<th class="table_header">Name</th>
					<th class="table_header">Email</th>
					<th class="table_header">Control</th>
				</tr>
				
				<% @users.each do |user| %>
					<tr>
						<td><%= user.name %></td>
						<td><%= user.email %></td>
						<td>
							<%= user.link_to_show %>
							<% if is_admin? %>
								 -  <%= user.link_to_edit %> - <%= user.link_to_delete %>
							<% else %>
								<% if user.id == session[:user_id] %>
								 - <%= user.link_to_edit %>
								<% end %>
							<% end %>		 	
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Add User') %>
<% provide(:heading, 'Add User') %>
<% provide(:subheading, 'Add User to Clean Blog') %>
<% provide(:bg, 'about-bg.jpg') %>
<% provide(:url_target, users_path) %>
<% provide(:method, :post) %>

<%= render 'form' %>

app/views/users/show.html.erb
<% provide(:title, 'View User') %>
<% provide(:heading, 'View User') %>
<% provide(:subheading, 'User of Clean Blog') %>
<% provide(:bg, 'about-bg.jpg') %>

<div class="container text-center">
	<p>
	  <strong>Name :</strong>
	  <%= @user.name %>
	</p>
	 
	<p>
	  <strong>Email :</strong>
	  <%= @user.email %>
	</p>

	<div>
		<% if is_admin? || @user.id == session[:user_id] %>
			<%= @user.link_to_edit %> |
		<% end %>
		<%= @user.link_to_index %>
	</div>
</div>