config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'pages#index'

  resources :users
  resources :blog_posts

  get '/about', to: 'pages#about'
  get '/sample_blog_post', to: 'pages#sample_blog_post'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/user_profile', to: 'sessions#show'
  get '/user_profile/edit', to: 'sessions#edit'
  patch '/user_profile', to: 'sessions#update'
  get '/recent_blog', to: 'pages#recent_blog'
  get '/dashboard', to: 'pages#dashboard'
  get '/import', to: 'blog_posts#upload'
  post '/import', to: 'blog_posts#import'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<hr>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <%= link_to "Start Bootstrap", root_path, class: "navbar-brand"%>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <nav>
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Home",         root_path %></li>
                    <li><%= link_to "Dashboard",    dashboard_path %></li>
                    <li><%= link_to "User",         users_path if logged_in? %></li>
                    <li><%= link_to "Blog Post",    blog_posts_path if logged_in? %></li>
                    <li><%= link_to "About",        about_path %></li>
                    <li><%= link_to "Log in",       login_path if !logged_in? %></li>
                    <li><%= link_to "User Profile", user_profile_path if logged_in? %></li>
                    <li><%= link_to 'Logout',       logout_path,
                            method: :delete,
                            data: { confirm: 'Are you sure to log out?' } if logged_in? %></li>
                </ul>
            </nav>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <%= site_heading(yield(:title)) %>
            </div>
        </div>
    </div>
</header>

<% if yield(:title) == 'Blog Post' %>
    <style type="text/css">
        .intro-header {
            background-image: url(<%= yield(:bg) %>)
        }
    </style>
<% else %>
    <style type="text/css">
        .intro-header {
            background-image: url(<%= image_path(yield(:bg)) %>)
        }
    </style>
<% end %>

app/views/layouts/_post_head.html.erb
<div class="post-heading">
    <h1><%= yield(:post_title) %></h1>
    <h2 class="subheading"><%= yield(:post_summary) %></h2>
    <span class="meta">Posted by <a href="#"><%= yield(:poster) %></a> on <%= yield(:date_created) %></span>
</div>

app/views/layouts/_site_head.html.erb
<div class="site-heading">
    <h1><%= yield(:heading) %></h1>
    <hr class="small">
    <span class="subheading"><%= yield(:subheading) %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <% update_activity if logged_in? %>
  	<%= render 'layouts/header' %>
  	<%= yield %>
    <%= render 'layouts/footer' %>
  </body>
  <%= javascript_include_tag 'application' %>
</html>